@startuml classes-marblerunlist

!include style.plantuml

' Interfaces

interface MarbleRunListWireframeProtocol <<Wireframe>> {
    {static} createMarbleRunListModule(in: ARInteractionMode) -> UIViewController
    presentARView(from: MarbleRunListViewProtocol, with: MarbleRunEntity)
}

interface MarbleRunListViewProtocol <<View>> {
    presenter : MarbleRunListPresenterProtocol?
    canAddNew : Bool
    reloadMarbleRunList(with: [MarbleRunEntity])
}

interface MarbleRunListPresenterProtocol <<Presenter>> {
    view : MarbleRunListViewProtocol?
    wireframe : MarbleRunListWireframeProtocol?
    interactor : MarbleRunListInteractorProtocol?
    viewDidLoad()
    didSelect(marblerun: MarbleRunEntity, on: MarbleRunListViewProtocol)
    didSelectNew(with: String, on: MarbleRunListViewProtocol)
}

interface MarbleRunListInteractorProtocol <<Interactor>> {
    retrieveMarbleRuns(_: ([MarbleRunEntity]) -> Void)
    createNewMarbleRun(with: String) -> MarbleRunEntity
}

interface UICollectionViewDataSource {
    collectionView(_: UICollectionView, numberOfItemsInSection: Int) -> Int
    collectionView(_: UICollectionView, cellForItemAt: IndexPath) -> UICollectionViewCell
}

interface UICollectionViewDelegate {
    collectionView(_: UICollectionView, didSelectItemAt: IndexPath)
}

' Classes

class MarbleRunListWireframe <<Wireframe>> {
    {static} mainStoryboard: UIStoryboard
    mode : ARInteractionMode
    init(with: ARInteractionMode)
}

class MarbleRunListView <<View>> {
    marblerunMarbleRunList: [MarbleRunEntity]
    collectionView: UICollectionView!
    showNewDialogue()
}

class MarbleRunListPresenter <<Presenter>>

class MarbleRunListInteractor <<Interactor>>

' Relationships

MarbleRunListViewProtocol -r-> MarbleRunListPresenterProtocol
MarbleRunListPresenterProtocol -l-> MarbleRunListViewProtocol
MarbleRunListPresenterProtocol --> MarbleRunListInteractorProtocol
MarbleRunListWireframeProtocol <-u-- MarbleRunListPresenterProtocol

' Implementations

MarbleRunListWireframe .u.|> MarbleRunListWireframeProtocol
MarbleRunListView ..u..|> MarbleRunListViewProtocol
MarbleRunListPresenter .u..|> MarbleRunListPresenterProtocol
MarbleRunListInteractor .u.|> MarbleRunListInteractorProtocol

MarbleRunListView .|> UICollectionViewDataSource
MarbleRunListView ..|> UICollectionViewDelegate

@enduml
