@startuml project-viper-architecture

!include style.plantuml

frame "other Modules" {
	class otherWireframe <<Wireframe>>
}

frame Module {
	class Wireframe <<Wireframe>>
	class Presenter <<Presenter>>
	class View <<View>>
	class Interactor <<Interactor>>

	otherWireframe <-r-> Wireframe : knows
	Wireframe <-- Presenter : owns
	View <- Presenter : weak reference
	View -> Presenter : "owns"
	Presenter -> Interactor : owns
	Wireframe ..> Wireframe : creates
	Wireframe ..> Presenter : creates
	Wireframe ..> View : creates
	Wireframe ..> Interactor : creates
}

frame Common {
	class DataManager
	Interactor -> DataManager : uses
}

frame Entities {
	class Entity
	DataManager -u-> Entity : knows about
}

@enduml
