@startuml project-structure

!include style.plantuml

package Entities {}

package Nodes {
	class BoundingBoxNode
	class MarbleRunNode
	class ElementNode
	class PlaneNode
}

package Common {
	class LocalDataManager
	class Triple
	class ARInteractionMode
	class ElementProtocol
	class ARViewController
	class DepthFirstSort
	class Initializer
	class ARModeState
}

package Modules {
	package ElementList {
		class ElementListWireframe
		class ElementListView
		class ElementListPresenter
		class ElementListInteractor
	}
	package MarbleRunList {
		class MarbleRunListWireframe
		class MarbleRunListView
		class MarbleRunListPresenter
		class MarbleRunListInteractor
	}
	package SelectMode {
		class SelectModeWireframe
		class SelectModeView
		class SelectModePresenter
	}
	package AREditor {
		class AREditorWireframe
		class AREditorView
		class AREditorPresenter
		class AREditorInteractor
	}
	package ARGuide {
		class ARGuideWireframe
		class ARGuideView
		class ARGuidePresenter
		class ARGuideInteractor
	}
}

@enduml
