skinparam Shadowing false
'skinparam DefaultFontName "Source Sans Pro"
skinparam DefaultFontName "SF Mono"
skinparam dpi 150
skinparam partitionBackgroundColor white

skinparam Class {
	BorderColor black
'	BorderThickness 1
	ArrowColor black
	BackgroundColor white
	FontStyle bold
	StereotypeFontSize 10
	ArrowFontSize 10
	AttributeIconSize 0
	HeaderBackgroundColor<<Wireframe>> #46B29D
	HeaderBackgroundColor<<View>>  #DE5B49
	HeaderBackgroundColor<<Interactor>> #F0CA4D
	HeaderBackgroundColor<<Presenter>> #E37B40
}

skinparam Component {
	BorderColor black
	BackgroundColor white
}

hide empty fields
hide empty methods
hide circle
hide stereotype
